### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by agriyakhetarpal** [huggingface/chat-macOS#12]
## Description

While this might or might not rely on https://github.com/huggingface/chat-macOS/issues/9, it would be great if this project could supply a Homebrew formula for installation purposes, sometime down the road. This way, the [GitHub released/tagged binaries](https://github.com/huggingface/chat-macOS/releases/tag/v0.5.0) would be available as Homebrew casks to download via a `brew install --cask huggingchat` (or similar) command in a macOS terminal.

## See also

- https://docs.brew.sh/Taps
- https://docs.brew.sh/Adding-Software-to-Homebrew#casks

**Comment by Vaibhavs10** [comment]
Wonderful suggestion @agriyakhetarpal - would you like to take this up? 🤗 
We can start with a tap and then move it to the main brew repo, ofc.

**Comment by agriyakhetarpal** [comment]
Absolutely! I'll plan to start working on this as soon as next week. Please feel free to assign me to this.

**Comment by Vaibhavs10** [comment]
How's it going with the brew setup @agriyakhetarpal ? 🤗

**Comment by agriyakhetarpal** [comment]
I've started working on it, and it's coming along well; thanks for seeking a follow-up, @Vaibhavs10! It's my first time setting up a Homebrew formula/cask and a tap, so the docs are still a little murky to me. I'll share a branch as soon as I have something concrete.

Should we consider starting a `homebrew-` prefixed repository, by the way? The Homebrew docs recommend it if we want a shorthand for the `brew tap` command: https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions.

**Comment by agriyakhetarpal** [comment]
I just wished to inform those subscribed here that this is still on my radar, I've just been away on vacation for some time! I do intend to work on this further 😃

**Comment by BlueSkiesLife** [comment]
Hey [agriyakhetarpal](https://github.com/agriyakhetarpal), it seems that it already got added. 

brew install --cask huggingchat

**Comment by agriyakhetarpal** [comment]
Thanks! Apologies, I couldn't get to this sooner. It's great to see it added and kudos to the person who ended up doing this in my absence.
