### ISSUE TITLE
Move the message section on the screen.

### ISSUE THREAD

**Issue by efeecllk** [huggingface/chat-macOS#2]
Since moving the message section within the screen could be an important feature, I opened an issue. @cyrilzakka 

Thanks again for positive feedback

Best.

**Comment by varungupta31** [comment]
It is already movable.

<img width="497" alt="Screenshot 2024-09-24 at 11 27 00 PM" src="https://github.com/user-attachments/assets/b8d8d32c-f6ce-4950-9ecf-591cfc52e47f">

Dragging this around works, and the new position persists as well.

**Comment by efeecllk** [comment]
I actually tried this before, I think it's a problem with my computer. Thanks
