### ISSUE TITLE
Local model(llama-3.2-3b-instruct) output content is chaotic

### ISSUE THREAD

**Issue by Lsnsh** [huggingface/chat-macOS#27]
Local model(llama-3.2-3b-instruct) output content is chaotic, but server-side model work normal.

**Local Model:**

GGUF Model: `llama-3.2-3b-instruct-q4_k_m`

![output](https://github.com/user-attachments/assets/32f973fb-d554-4b89-bcee-fcbc13cb0dd6)

https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF

**Server-Side Model:** 

HuggingFace: Meta-Llama-3.1-70B-Instruct, Qwen2.5-72B-Instruct

---

https://github.com/user-attachments/assets/1353bdf3-4bde-4b9d-8c2c-10f61da288e1

**Comment by cyrilzakka** [comment]
Thanks for highlighting this issue! Did this behavior happen right out of the start of the new conversation or after a few back and forths?

**Comment by Lsnsh** [comment]
> Thanks for highlighting this issue! Did this behavior happen right out of the start of the new conversation or after a few back and forths?感谢您强调这个问题！这种行为是在新对话开始时发生的还是在几次来回之后发生的？

Occurred when starting a new conversation.

**Comment by Lsnsh** [comment]
After a few back and forth, there were other abnormal situations that occurred. I can open a separate issue.

**Comment by cyrilzakka** [comment]
Have now switched to an MLX local backend. Should be more stable- please let me know how it is. You'll have to build from source for now
