### ISSUE TITLE
Does this work on local model?

### ISSUE THREAD

**Issue by jsomedon** [huggingface/chat-macOS#32]
It's not clear from README nor the demo video.

**Comment by cyrilzakka** [comment]
Now supports MLX inference. Press `CMD+Shift+\ `to switch to local inference

**Comment by ibehnam** [comment]
It doesn't work. I have ollama and lm studio and it won't work.

**Comment by cyrilzakka** [comment]
Hi @ibehnam would you mind giving me more details? You first have to download a model from the components pane in Settings (right click on the HFIcon in the menu bar). Once a model is downloaded, you can enable it in the General page under local generation (and the shortcut will now work)

**Comment by thelazyoxymoron** [comment]
I only see two language models and one audio models and no way to specify a custom model.

<img width="494" alt="Screenshot 2024-12-10 at 11 45 21 AM" src="https://github.com/user-attachments/assets/5ae3517e-524d-4b05-acae-2f770ec9fbfe">
