### ISSUE TITLE
Is there a plan to release source code like swift-chat?

### ISSUE THREAD

**Issue by eagle705** [huggingface/chat-macOS#9]
I would like to use this project with customization.

I'm wondering whether hf has a plan to release swift code too (like [swift-chat](https://github.com/huggingface/swift-chat))

**Comment by osanseviero** [comment]
Yes 🔥

**Comment by tisfeng** [comment]
Thanks, hope to see the source code soon 😃

**Comment by cyrilzakka** [comment]
@tisfeng Done :)

**Comment by tisfeng** [comment]
Great 👍
